#pragma once

#include "EquilTriangle.h"
#include "Rectangle.h"
#include "IsoTriangle.h"
#include "Square.h"
#include "Pentagon.h"
#include "Hexagon.h"
#include "Star.h"
#include "Arrow.h"
#include "Circle.h"
#include "Ellipse.h"
#include "Add.h"
#include "Minus.h"
#include "Multiply.h"
#include "Line.h"
#include "Devide.h"